apiVersion: v1
kind: Namespace
metadata:
  name: ddev
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: redis
  namespace: ddev
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
---
kind: Service
apiVersion: v1
metadata:
  name: redis
  namespace: ddev
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: app
  namespace: ddev
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: ui
        image: gnschenker/ddev-service-discovery-kube:1.0
        ports:
        - containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: app
  namespace: ddev
spec:
  selector:
    app: app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: NodePort
