apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  containers:
  - name: liveness
    image: gnschenker/liveness:1.0
    livenessProbe:
      exec:
        command:
        - curl
        - -f
        - http://localhost:8000/health
      initialDelaySeconds: 5
      periodSeconds: 5