apiVersion: v1
kind: Namespace
metadata:
  name: ddev
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: app
  namespace: ddev
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: ui
        image: gnschenker/ddev-secrets-kube:1.0
        env:
        - name: AUTHTOKEN
          value: /run/secrets/access_token
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: github-token-volume
          mountPath: "/run/secrets"
          readOnly: true
      volumes:
      - name: github-token-volume
        secret:
          secretName: github-token
          items:
          - key: access_token.txt
            path: access_token
---
kind: Service
apiVersion: v1
metadata:
  name: app
  namespace: ddev
spec:
  selector:
    app: app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: NodePort
